nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PATCH', 'DELETE', 'OPTIONS']
        allow_credentials: true
        expose_headers: []
        max_age: 1
    paths:
        '^/api/':
            allow_origin: [ '*' ]
            allow_headers: [ '*' ]
            allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE', 'OPTIONS' ]
            max_age: 1
