security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
      
    login:
      pattern: ^/api/login
      stateless: true
      json_login:
        check_path: /api/login
        username_path: username
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
        provider: app_user_provider

    api:
      pattern: ^/api
      stateless: true
      jwt: ~
      provider: app_user_provider

    main:
      lazy: true
      provider: app_user_provider
      form_login:
        login_path: admin_login
        check_path: admin_login
        default_target_path: admin
        always_use_default_target_path: true
      logout:
        path: app_logout

  access_control:
    - { path: ^/admin/login, roles: PUBLIC_ACCESS }
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/api/collections/public, roles: PUBLIC_ACCESS, methods: [GET] }
    - { path: ^/api/login, roles: PUBLIC_ACCESS }
    - { path: ^/api/docs, roles: PUBLIC_ACCESS } # Swagger UI
    - { path: ^/api/verify_email, roles: PUBLIC_ACCESS } # Swagger UI
    - { path: ^/api/contexts, roles: PUBLIC_ACCESS }  # Pour les contextes JSON-LD
    - { path: ^/api, roles: ROLE_USER }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4 # Lowest possible value for bcrypt
        time_cost: 3 # Lowest possible value for argon
        memory_cost: 10 # Lowest possible value for argon