vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        collectables_pictures:
            uri_prefix: /images/collectables
            upload_destination: '%kernel.project_dir%/public/images/collectables'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer